config/routes.rb
Rails.application.routes.draw do

  resources :authors, only: [:index]
  get '/authors/new', to: 'authors#new', as: 'new_author'
  post '/authors', to: 'authors#create', as: 'create_author'
  get '/authors/:id', to: 'authors#show', as: 'author'
  get '/authors/:id/edit', to: 'authors#edit', as: 'edit_author'
  patch '/authors/:id', to: 'authors#update', as: 'update_author'
  delete '/authors/:id', to: 'authors#destroy', as: 'destroy_author'
  
  resources :books, only: [:index]
  get '/books/new', to: 'books#new', as:'new_book'
  post '/books', to: 'books#create', as: 'create_book'
  get '/books/:id', to: 'books#show', as: 'book'
  get '/books/:id/edit', to: 'books#edit', as: 'edit_book'
  patch '/books/:id', to: 'authors#update', as: 'update_book'
  delete '/books/:id', to: 'authors#destroy', as: 'destroy_book'
  get 'index_json', to: 'books#index_json'
  
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :book

    validates :author_name, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :author

    validates :title, presence: { message: "can't be blank" }, length: { maximum: 50 }
    validates :publication_year, presence: { message: "can't be blank" }, length: { is: 4 }
    validates :author_id, presence: { message: "author must be assigned" }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true
    validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    validates :password, presence: true, length: { minimum: 8 }
    
    def new_attr
        id:,
        email:,
        username:
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def set_pagination_params
        params[:page] = params[:page].to_i.positive? ? params[:page] : 1
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    def index
      @authors = Author.paginate(page: params[:page], per_page: 10)
    end

    def new
      @author = Author.new
    end

    def show
      @author = Author.find(params[:id])
    end

    def create
      @author = Author.new(author_params)
  
      if @author.save
        redirect_to authors_path, notice: 'Penulis berhasil ditambahkan.'
      else
        render 'new'
      end
    end

    def edit
      @author = Author.find(params[:id])
    end    

    def update
      @author = Author.find(params[:id])
    
      if @author.update(author_params)
        redirect_to authors_path, notice: 'Penulis berhasil diperbarui.'
      else
        render 'edit'
      end
    end    

    def destroy
      @author = Author.find(params[:id])
      @author.destroy
    
      redirect_to authors_path, notice: 'Penulis berhasil dihapus.'
    end    

    private
    
    def set_author
        @author = Author.find(params[:id])
        return unless @author.nil?
    
        render json: { status: 404, message: 'author not found' }, status: 404
    end

    def author_params
      params.require(:author).permit(:author_name)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.paginate(page: params[:page], per_page: 10)
  end

  def index_json
    @books = Book.all
    render json: @books
  end

  def show
    # Aksi ini akan menampilkan detail buku berdasarkan ID
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_path, notice: 'Buku berhasil ditambahkan.'
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    if @book.update(book_params)
      redirect_to books_path, notice: 'Buku berhasil diperbarui.'
    else
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: 'Buku berhasil dihapus.'
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :publication_year, :author_id)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
        @users = User.all
        if @users.present?
          render json: { success: true, message: 'data found', status: 200, data: user.new_attr }
        else
          render json: { success: true, message: 'data not found', status: 404 }, status: 404
        end
    end
    def create
        @user = User.new(user_params)
        if @user.save
          render json: { success: true, status: 201, message: 'user created successfully', data: @user.new_attr },
                 status: 201
        else
          render json: { success: false, status: 422, message: 'oooppss, something went wrong!', data: @user.errors.full_messages.first },
                 status: 422
        end
    end

    def user_params
        params.permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/authors/edit.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Edit Penulis</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- Brand/logo -->
      <a class="navbar-brand" href="#">My Library</a>
      
      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Daftar Penulis', authors_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Daftar Buku', books_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-- app/views/authors/edit.html.erb -->
<div class="container mt-5">
  <h1>Edit Penulis</h1>

  <%= form_with(model: @author, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :author_name, 'Nama Penulis' %>
      <%= form.text_field :author_name, class: 'form-control' %>
    </div>

    <%= form.submit 'Simpan', class: 'btn btn-primary' %>
    <%= link_to 'Kembali', authors_path, class: 'btn btn-secondary' %>
  <% end %>
</div>

</body>
</html>

app/views/authors/index.html.erb
<!-- app/views/authors/index.html.erb -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Daftar Penulis</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- Brand/logo -->
      <a class="navbar-brand" href="#">My Library</a>
      
      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Daftar Penulis', authors_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Daftar Buku', books_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container mt-5">
    <h1 class="mb-4">Daftar Penulis</h1>
    <%= link_to 'Tambah Penulis', new_author_path, class: 'btn btn-success mb-4' %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Nama Penulis</th>
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        <% @authors.each_with_index do |author, index| %>
          <tr>
            <td><%= author.id %></td>
            <td><%= author.author_name %></td>
            <td>
                <%= link_to 'Edit', edit_author_path(author), class: 'btn btn-warning btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <!-- Pagination links -->
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        <%= will_paginate @books, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </ul>
    </nav>
  </div>

  <!-- Script Bootstrap JS (Pastikan Anda sudah mengimpor JS Bootstrap jika belum) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-3R9j9Xz4S5F5m5Oj3zdzgHd5z5sm8b8fzb5t78EF5PZbzqF5CqzW5F5B6a0b5I3L1" crossorigin="anonymous"></script>
</body>
</html>

app/views/authors/new.html.erb
<!-- app/views/authors/new.html.erb -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Tambah Penulis</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- Brand/logo -->
      <a class="navbar-brand" href="#">My Library</a>
      
      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Daftar Penulis', authors_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Daftar Buku', books_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-5">
    <h1 class="mb-4">Tambah Penulis</h1>
    <%= form_with model: @author, url: authors_path, method: :post, class: 'needs-validation', novalidate: true do |form| %>
      <% if @author.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @author.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="mb-3">
        <%= form.label :author_name, class: 'form-label' %>
        <%= form.text_field :author_name, class: 'form-control', required: true %>
      </div>

      <div class="mb-3">
        <%= form.submit 'Tambah Penulis', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

  <script>
    // Validasi form sisi klien menggunakan HTML5 constraints
    // Anda dapat menambahkan logika validasi kustom di sini jika diperlukan
  </script>
</body>
</html>

app/views/books/edit.html.erb
<!-- app/views/layouts/application.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Edit Buku</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
<!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- Brand/logo -->
      <a class="navbar-brand" href="#">My Library</a>
      
      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Daftar Penulis', authors_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Daftar Buku', books_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<div class="container mt-5">
  <h1>Edit Buku</h1>

  <%= form_with(model: @book, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :title, 'Judul' %>
      <%= form.text_field :title, class: 'form-control', value: @book.title %>
    </div>
    <div class="form-group">
      <%= form.label :publication_year, 'Tahun Terbit' %>
      <%= form.number_field :publication_year, class: 'form-control',value: @book.publication_year %>
    </div>
    <div class="form-group">
      <%= form.label :author_id, 'Penulis' %>
      <%= form.collection_select :author_id, Author.all, :id, :author_name, { prompt: 'Pilih penulis' }, { class: 'form-select', selected: @book.author_id } %>
    </div>

    <%= form.submit 'Simpan', class: 'btn btn-primary mt-3' %>
    <%= link_to 'Kembali', books_path, class: 'btn btn-secondary mt-3' %>
  <% end %>
</div>

</body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Library</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- Brand/logo -->
      <a class="navbar-brand" href="#">My Library</a>
      
      <!-- Toggler/collapsible Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Daftar Penulis', authors_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Daftar Buku', books_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <h1 class="mt-5 mb-4">Daftar Buku</h1>
    <%= link_to 'Tambah Buku Baru', new_book_path, class: 'btn btn-success' %>
    <!-- Tabel Daftar Buku -->
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">No.</th>
          <th scope="col">Judul</th>
          <th scope="col">Tahun Terbit</th>
          <th scope="col">Penulis</th>
          <th scope="col">Aksi</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each_with_index do |book, index| %>
          <tr>
            <td><%= book.id %></td>
            <td><%= book.title %></td>
            <td><%= book.publication_year %></td>
            <td><%= book.author.author_name %></td>
            <td>
              <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-warning btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!-- Pagination links -->
    <nav aria-label="Page navigation">
      <ul class="pagination justify-content-center">
        <%= will_paginate @books, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </ul>
    </nav>

  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-3R9j9Xz4S5F5m5Oj3zdzgHd5z5sm8b8fzb5t78EF5PZbzqF5CqzW5F5B6a0b5I3L1" crossorigin="anonymous"></script>
</body>
</html>

app/views/books/new.html.erb
<!-- app/views/books/create.html.erb -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Library - Add a New Book</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <!-- Brand/logo -->
      <a class="navbar-brand" href="#">My Library</a>
      
      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar links -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Daftar Penulis', authors_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Daftar Buku', books_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container mt-5">
    <h1 class="mb-4">Add a New Book</h1>
    <%= form_with model: @book, url: books_path, method: :post, class: 'needs-validation', novalidate: true do |form| %>
      <% if @book.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <div class="mb-3">
        <%= form.label :title, class: 'form-label' %>
        <%= form.text_field :title, class: 'form-control', required: true %>
      </div>

      <div class="mb-3">
        <%= form.label :publication_year, class: 'form-label' %>
        <%= form.number_field :publication_year, class: 'form-control', required: true %>
      </div>

      <div class="mb-3">
        <%= form.label :author_id, class: 'form-label' %>
        <%= form.collection_select :author_id, Author.all, :id, :author_name, { prompt: 'Select an author' }, { class: 'form-select', required: true } %>
      </div>

      <div class="mb-3">
        <%= form.submit 'Add Book', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

  <script>
    // Client-side form validation using HTML5 constraints
    // You can add custom validation logic here if needed
  </script>
</body>
</html>